# Name(s)
Quinn Coleman

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE** - later

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [2]:
import numpy as np

a = np.full((6, 4), 2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [3]:
b = np.ones((6, 4), dtype=int)
np.fill_diagonal(b, 3)
b

array([[3, 1, 1, 1],
       [1, 3, 1, 1],
       [1, 1, 3, 1],
       [1, 1, 1, 3],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Exercise 3

In [4]:
a * b
# np.dot(a,b)

array([[6, 2, 2, 2],
       [2, 6, 2, 2],
       [2, 2, 6, 2],
       [2, 2, 2, 6],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

- dot(a,b) doesn't work because that is a dot product that requires matrices a and b to have aligned dimensions.
- a * b works because that is an element-wise multiplication and matrices a and b have the same dimensions.

## Exercise 4

In [5]:
a
a.transpose()
b
b.transpose()
display(np.dot(a.transpose(), b))
np.dot(a, b.transpose())

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

array([[12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8]])

The shapes are different because they are results of different dot products.

## Exercise 5

In [6]:
def cool_func():
    print('This is a pretty cool function')
    
cool_func()

This is a pretty cool function


## Exercise 6

In [13]:
def do_matrix_stuff():
    a = np.random.rand(3,4)
    b = np.random.rand(2,5)
    print('Sum of a:', np.sum(a)) 
    print('Sum of b:', b.sum()) # Same op - Python built-in
    print('Mean of a:', np.mean(b))
    print('Mean of b:', b.mean()) # Same op - Python built-in
    print('Median of a:', np.median(a))
    print('Median of b:', np.median(b)) # No Python built-in
    
do_matrix_stuff()

Sum of a: 6.721509658776518
Sum of b: 4.696413500766834
Mean of a: 0.4696413500766834
Mean of b: 0.4696413500766834
Median of a: 0.56004658284989
Median of b: 0.5094573453518253


## Exercise 7

In [23]:
def count_ones(array):
    return np.array([1 if elem == 1 else 0 for elem in list(array)]).sum()
         
a = np.arange(9)

display(count_ones(a))
np.sum(np.where(a == 1, 1, 0))

1

1

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE