# Name(s)
Quinn Coleman

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE** - later

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [2]:
import numpy as np

a = np.full((6, 4), 2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

## Exercise 2

In [3]:
b = np.ones((6, 4), dtype=int)
np.fill_diagonal(b, 3)
b

array([[3, 1, 1, 1],
       [1, 3, 1, 1],
       [1, 1, 3, 1],
       [1, 1, 1, 3],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Exercise 3

In [4]:
a * b
# np.dot(a,b)

array([[6, 2, 2, 2],
       [2, 6, 2, 2],
       [2, 2, 6, 2],
       [2, 2, 2, 6],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

- dot(a,b) doesn't work because that is a dot product that requires matrices a and b to have equal inner dimensions.
- a * b works because that is an element-wise multiplication and matrices a and b have the same dimensions.

## Exercise 4

In [5]:
a
a.transpose()
b
b.transpose()
display(np.dot(a.transpose(), b))
np.dot(a, b.transpose())

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

array([[12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8],
       [12, 12, 12, 12,  8,  8]])

The shapes are different because they are results of different dot products.

## Exercise 5

In [6]:
def cool_func():
    print('This is a pretty cool function')
    
cool_func()

This is a pretty cool function


## Exercise 6

In [7]:
def do_matrix_stuff():
    a = np.random.rand(3,4)
    b = np.random.rand(2,5)
    print('Sum of a:', np.sum(a)) 
    print('Sum of b:', b.sum()) # Same op - Python built-in
    print('Mean of a:', np.mean(b))
    print('Mean of b:', b.mean()) # Same op - Python built-in
    print('Median of a:', np.median(a))
    print('Median of b:', np.median(b)) # No Python built-in
    
do_matrix_stuff()

Sum of a: 6.570438754612023
Sum of b: 6.856430329018204
Mean of a: 0.6856430329018204
Mean of b: 0.6856430329018204
Median of a: 0.5075051691885681
Median of b: 0.7203761473786691


## Exercise 7

In [8]:
def count_ones(array):
    counter = 0
    for i in range(array.shape[0]):
        for j in range(array.shape[1]):
            if array[i,j] == 1:
                counter += 1
    return counter

         
a = np.arange(9).reshape(3,3)

display(count_ones(a))
np.sum(np.where(a == 1, 1, 0))

1

1

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [12]:
import pandas as pd

a_matrix = np.full((6, 4), 2)
a = pd.DataFrame(a_matrix)
a

0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [13]:
b_matrix = np.ones((6, 4), dtype=int)
b_matrix[np.arange(4), np.arange(4)] = 3
b = pd.DataFrame(b_matrix)
b

0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [15]:
a * b
# a.dot(b)

ValueError: matrices are not aligned

The same results happen, for the same reasons as with the numpy array implementation:
- dot(a,b) doesn't work because that is a dot product that requires matrices a and b to have equal inner dimensions.
- a * b works because that is an element-wise multiplication and matrices a and b have the same dimensions.

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [28]:
# Can use np.where or pd.where
def count_ones(dataframe):
    counter = 0
    for i in range(dataframe.shape[0]):
        for j in range(dataframe.shape[1]):
            if dataframe.iloc[i,j] == 1:
                counter += 1
    return counter

a = pd.DataFrame(np.arange(9).reshape(3,3))

display(count_ones(a))
a.where(a == 1, 0).sum().sum()

1

1

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [30]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [31]:
titanic_df.name

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [37]:
titanic_df.set_index('sex',inplace=True)
len(titanic_df.loc['female'])

466

## Exercise 14
How do you reset the index?

In [38]:
titanic_df.reset_index(inplace=True)
titanic_df.head()

sex  pclass  survived                                             name  \
0  female       1         1                    Allen, Miss. Elisabeth Walton   
1    male       1         1                   Allison, Master. Hudson Trevor   
2  female       1         0                     Allison, Miss. Helen Loraine   
3    male       1         0             Allison, Mr. Hudson Joshua Creighton   
4  female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON